export const projects = [
  {
    number: "/01",
    title: "Scarab",
    description: "Release note tracking",
    year: "2023",
    type: "DESIGN & DEVELOPMENT",
    url: "",
    imageUrl: "",
    altText: "Project 1",
  },
  {
    number: "/02",
    title: "Arcane",
    description: "Newsletter automation",
    year: "2023",
    type: "DESIGN & DEVELOPMENT",
    url: "https://github.com/kelvinyelyen/arcane",
    imageUrl: "",
    altText: "Project 2",
  },
  {
    number: "/03",
    title: "Muzeyi",
    description: "Client / Portfolio",
    year: "2023",
    type: "DESIGN & DEVELOPMENT",
    url: "https://www.muzeyiyelyen.com/",
    imageUrl: "",
    altText: "Project 3",
  },
]

export const archived = [
  {
    number: "/01",
    title: "Kinde-auth",
    description: "Kinde Nextjs SDK starter",
    year: "2023",
    type: "DESIGN & DEVELOPMENT",
    url: "https://kinde-auth.vercel.app/",
    imageUrl: "",
    altText: "Project 1",
  },
  {
    number: "/02",
    title: "Next-auth",
    description: "NextAuth integration w/ Prisma...",
    year: "2023",
    type: "DESIGN & DEVELOPMENT",
    url: "https://github.com/kelvinyelyen/trace-dependencies",
    imageUrl: "",
    altText: "Project 2",
  },
  {
    number: "/03",
    title: "Atlas",
    description: "Streamlined weather",
    year: "2023",
    type: "DESIGN & DEVELOPMENT",
    url: "https://atlasweatherfocus.vercel.app/",
    imageUrl: "",
    altText: "Project 3",
  },
  {
    number: "/04",
    title: "Electronic Health Registry",
    description: "Final year project",
    year: "2021",
    type: "RESEARCH & DEVELOPMENT",
    url: "https://drive.google.com/file/d/1OfbmOqsmnb479wTh7FYDjtCgKnx1dJPR/view?usp=sharing",
    imageUrl: "images/ehr.png",
    altText: "Project 4",
  },
]
