export const projects = [
  {
    number: "01",
    title: "Scarab",
    description: "Building an open-source release note tracker",
    year: "2023",
    role: "Creator",
    url: "https://github.com/kelvinyelyen/scarab",
    imageUrl: "",
    altText: "Project 1",
  },
  {
    number: "02",
    title: "Arcane",
    description: "Newsletter automation with Python",
    year: "2023",
    role: "Creator",
    url: "https://github.com/kelvinyelyen/arcane",
    imageUrl: "",
    altText: "Project 2",
  },
  {
    number: "03",
    title: "Muzeyi",
    description: "Client / Portfolio",
    year: "2023",
    role: "Creator",
    url: "https://www.muzeyiyelyen.com/",
    imageUrl: "",
    altText: "Project 3",
  },
]

export const archived = [
  {
    number: "01",
    title: "Kinde-auth",
    description:
      "Robust authentication boilerplate for modern Next.js web apps",
    year: "2023",
    role: "Creator",
    url: "https://kinde-auth.vercel.app/",
    imageUrl: "",
    altText: "Project 1",
  },
  {
    number: "02",
    title: "Next-auth",
    description: "NextAuth Boilerplate Integration with Prisma, Vercel Postgres",
    year: "2023",
    role: "Creator",
    url: "https://nextjs-postgres-auth-sooty.vercel.app/",
    imageUrl: "",
    altText: "Project 2",
  },
  {
    number: "03",
    title: "Atlas",
    description: "Streamlined weather app, a visual experiment",
    year: "2023",
    role: "Creator",
    url: "https://atlasweatherfocus.vercel.app/",
    imageUrl: "",
    altText: "Project 3",
  },
  {
    number: "04",
    title: "EHR",
    description: "Undergrad thesis on Electronic Health Records",
    year: "2021",
    role: "Creator",
    url: "https://drive.google.com/file/d/1OfbmOqsmnb479wTh7FYDjtCgKnx1dJPR/view?usp=sharing",
    imageUrl: "images/ehr.png",
    altText: "Project 4",
  },
]
